# Your ROM file, should be in the same directory as run.bat
rompath: "Zelda no Densetsu - Kamigami no Triforce (Japan).sfc"
# The folder where you store your MSU Packs, allows for relative path (eg: ../../ALTTPR/MSU)
msupath: ""
# 1 : the script will automatically run the seed when saved / 0 : will only save the seed.
auto_start: 1
heart_speed:
    off: 0
    double: 0
    normal: 1
    half: 0
    quarter: 0
# If you don't care about some sprites, you can remove the corresponding line
# This corresponds to the sprites list available on https://alttpr.com/en/sprite_preview
sprite:
    Link: 0
    Four Swords Link: 0
    Abigail: 0
    Adol: 0
    Aggretsuko: 0
    Alice: 0
    Angry Video Game Nerd: 0
    Arcane: 0
    Ark: 0
    Arrghus: 0
    Astronaut: 0
    Badeline: 0
    Bananas In Pyjamas: 0
    Bandit: 0
    Batman: 0
    Beau: 0
    Bewp: 0
    Big Key: 0
    Birb: 0
    Birdo: 0
    Black Mage: 0
    Blacksmith Link: 0
    Blossom: 0
    Bob: 0
    Boo 2: 0
    Boo: 0
    Bottle o' Goo: 0
    BotW Zelda: 0
    Bowser: 0
    Branch: 0
    Brian: 0
    Broccoli: 0
    Bronzor: 0
    B.S. Boy: 0
    B.S. Girl: 0
    Bubbles: 0
    Bullet Bill: 0
    Buttercup: 0
    Cactuar: 0
    Cadence: 0
    CarlSagan42: 0
    Casual Zelda: 0
    Marvin the Cat: 0
    Cat Boo: 0
    CD-i Link: 0
    Celes: 0
    Charizard: 0
    Cheep Cheep: 0
    Chibity: 0
    Cirno: 0
    Clifford: 0
    Clyde: 0
    Conker: 0
    Cornelius: 0
    Corona: 0
    Cucco: 0
    Cursor: 0
    D.Owls: 0
    Dark Panda: 0
    Dark Boy: 0
    Dark Girl: 0
    Dark Link (Tunic): 0
    Dark Link: 0
    Dark Swatchy: 0
    Dark Zelda: 0
    Dark Zora: 0
    Deadpool (Mythic): 0
    Deadpool (SirCzah): 0
    Deadrock: 0
    Decidueye: 0
    Demon Link: 0
    Dragonite: 0
    Drake The Dragon: 0
    Eggplant: 0
    EmoSaru: 0
    Ezlo: 0
    Fierce Deity Link: 0
    Finn Merten: 0
    Finny Bear: 0
    Floodgate Fish: 0
    Flavor Guy: 0
    Fox Link: 0
    Freya Crescent: 0
    Frisk: 0
    Frog Link: 0
    Fujin: 0
    Future Trunks: 0
    Gamer: 0
    Mini Ganon: 0
    Ganondorf: 0
    Garfield: 0
    Garnet: 0
    Garo Master: 0
    GBC Link: 0
    Geno: 0
    Gobli: 0
    Goomba: 0
    Goose: 0
    GrandPOOBear: 0
    Gruncle Stan: 0
    Guiz: 0
    Hardhat Beetle: 0
    Hat Kid: 0
    Headless Link: 0
    Hello Kitty: 0
    Hidari: 0
    Hint Tile: 0
    Hitsuyan1337: 0
    Hoarder (Bush): 0
    Hoarder (Pot): 0
    Hoarder (Rock): 0
    Homer Simpson: 0
    Hyrule Knight: 0
    iBazly: 0
    Ignignokt: 0
    Informant Woman: 0
    Inkling: 0
    Invisible Link: 0
    Jack Frost: 0
    Jason Frudnick: 0
    Jasp: 0
    Jogurt: 0
    Katsura: 0
    Kecleon: 0
    Kenny McCormick: 0
    Ketchup: 0
    Kholdstare: 0
    King Gothalion: 0
    King Graham: 0
    Kirby: 0
    Kore8: 0
    Lakitu: 0
    Lapras: 0
    Lest: 0
    Lily: 0
    Linja: 0
    Hat Color Link: 0
    Tunic Color Link: 0
    Pony: 0
    Figaro Merchant: 0
    Lucario: 0
    Luigi: 0
    Madeline: 0
    Magus: 0
    Maiden: 0
    Mallow (Cat): 0
    Manga Link: 0
    Maple Queen: 0
    Marin: 0
    Mario (Classic): 0
    Tanooki Mario: 0
    Mario and Cappy: 0
    Marisa Kirisame: 0
    Matthias: 0
    Meatwad: 0
    Medallions: 0
    Medli: 0
    Megaman X: 0
    Baby Metroid: 0
    MewLp: 0
    Mike Jones: 0
    Minish Link: 0
    Minish Cap Link: 0
    missingno: 0
    Modern Link: 0
    Mog: 0
    Momiji Inubashiri: 0
    Moosh: 0
    Mouse: 0
    Ms. Paint Dog: 0
    Power Up with Pride Mushroom: 0
    Nature Link: 0
    Navi: 0
    Navirou: 0
    Ned Flanders: 0
    Negative Link: 0
    Neosad: 0
    NES Link: 0
    Ness: 0
    Nia: 0
    Niko: 0
    Old Man: 0
    Ori: 0
    Outline Link: 0
    Parallel Worlds Link: 0
    Paula: 0
    Princess Peach: 0
    Penguin Link: 0
    Pete: 0
    Phoenix Wright: 0
    Pikachu: 0
    Pink Ribbon Link: 0
    Piranha Plant: 0
    Plague Knight: 0
    Pokey: 0
    Popoi: 0
    Poppy: 0
    Porg Knight: 0
    Powerpuff Girl: 0
    Pride Link: 0
    Primm: 0
    Princess Bubblegum: 0
    Psyduck: 0
    The Pug: 0
    Purple Chest: 0
    Pyro: 0
    Rainbow Link: 0
    Remeer: 0
    Rick: 0
    Robo-Link 9000: 0
    Rocko: 0
    Rottytops: 0
    Roy Koopa: 0
    Rumia: 0
    Rydia: 0
    Ryu: 0
    Sailor Moon: 0
    Saitama: 0
    Samus (Super Metroid): 0
    Samus: 0
    Samus (Classic): 0
    Santa Link: 0
    Scholar: 0
    Selan: 0
    SevenS1ns: 0
    Shadow: 0
    Shadow Sakura: 0
    Shantae: 0
    Shuppet: 0
    Shy Gal: 0
    Shy Guy: 0
    SighnWaive: 0
    SNES Controller: 0
    Soda Can: 0
    Solaire of Astora: 0
    Hyrule Soldier: 0
    Sonic the Hedgehog: 0
    Sora: 0
    Sora (KH1): 0
    Squall: 0
    Squirrel: 0
    Squirtle: 0
    Stalfos: 0
    Stan: 0
    Static Link: 0
    Stick Man: 0
    Super Bomb: 0
    Super Bunny: 0
    Super Meat Boy: 0
    Swatchy: 0
    TASBot: 0
    Tea Time: 0
    Terra (Esper): 0
    Tetra: 0
    TGH: 0
    Thief: 0
    Thomcrow: 0
    Tile: 0
    Tingle: 0
    TMNT: 0
    Toad: 0
    Toadette: 0
    Captain Toadette: 0
    TotemLinks: 0
    Trogdor the Burninator: 0
    TP Zelda: 0
    TwoFaced: 0
    Ty the Tasmanian Tiger: 0
    Ultros: 0
    Valeera: 0
    VanillaLink: 0
    Vaporeon: 0
    Vegeta: 0
    Vera: 0
    Vitreous: 0
    Vivi: 0
    Vivian: 0
    Wario: 0
    Will: 0
    Wizzrobe: 0
    Wolf Link (Festive): 0
    Wolf Link (TP): 0
    Yoshi: 0
    Yunica Tovah: 0
    Zandra: 0
    Zebra Unicorn: 0
    Zeckemyro: 0
    Zelda: 0
    Zero Suit Samus: 0
    Zora: 0
menu_speed: # Only available when it's not a race ROM
    instant: 0
    fast: 0
    normal: 1
    slow: 0
heart_color:
    red: 1
    blue: 0
    green: 0
    yellow: 0
background_music:
    on: 1
    off: 0
quickswap: # Available if the preset allows quickswap
    on: 1
    off: 0
